### ISSUE TITLE
Push::DisconnectionError

### ISSUE THREAD

**Issue by ghost** [tompesman/push-core#27]
I get "Push::DisconnectionError, The APNs disconnected without returning an error."  error though I used correct certificate and valid device token. Also note that I'm on ubuntu OS.

**Comment by jakedunc** [comment]
We just found this issue posting and it helped us, so thanks. But a question is why is this needed for production? It seems backwards?

**Comment by tompesman** [comment]
A sandbox is to play around :wink: it's called like that in the apple documentation. I've used the same names as in the code so you can compare the two.
