### ISSUE TITLE
PEM: Configure with Passphrase

### ISSUE THREAD

**Issue by sbpipb** [tompesman/push-core#34]
Is there a passphrase parameter? I am unable to send push notifications.

**Comment by tompesman** [comment]
Please check: https://github.com/tompesman/push-apns/blob/master/lib/push/configuration_apns.rb#L3
The name of the parameter is: `certificate_password`

Cheers! :wink:

**Comment by sbpipb** [comment]
that was fast! thank you! @tompesman
