### ISSUE TITLE
Neither PUB key nor PRIV key: nested asn1 error

### ISSUE THREAD

**Issue by waleedarshad** [tompesman/push-core#35]
Hi,
I am receiving this error when i run bundle exec push development -f while using 'push-apns'
it also demand for pem pharse. how can i get rid to that???

*Neither PUB key nor PRIV key: nested asn1 error: /home/zen/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/push-apns-1.0.4/lib/push/daemon/apns_support/connection_apns.rb:101:in `initialize'
*

**Comment by tompesman** [comment]
While generating the certificates you can decide to use a password. If you leave that empty, no password will be required in your configuration.

See: https://github.com/tompesman/push-core#generating-certificates-for-apns
